ame: Web Automation Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-all-automation:
    runs-on: ubuntu-latest

    steps:
      # Download repository
      - name: Checkout Repository
        uses: actions/checkout@v3
    
      # Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
        
      # Setup Chrome
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v0.0.0
      
      # Setup Gradle if necessary
      - name: Setup Gradle Permissions
        run: chmod +x gradlew 

      # Execute Gradle command for running cucumber test
      - name: Execute Test
        run: ./gradlew web

      # Archive Test Result (Upload a Build Artifact, By: Action)
      - name: Archive Test Result
        uses: actions/upload-artifact@v3
        if: always() # This may be modified based on your requirements
        with:
          name: Cucumber Report
          path: reports
      
      # Deploy to Github Pages (Github Page Action, By: peaceiris)
      - name: Deploy report to Github Pages
        if: always() # This may be modified based on your requirements
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_DIR: reports
